version: '3.8'

services:
  backend:
    image: node:18.20-alpine3.20
    build: 
      context: ./backend
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app
      # - /app/node_modules
    command: yarn dev
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    image: node:18.20-alpine3.20
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    networks:
      - app-network
    command: yarn start
    volumes:
      - ./frontend:/app
      - /app/node_modules

  db:
    image: postgres:16-alpine3.20
    restart: always
    env_file:
      - .env
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d beer_pub"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
